language: node_js

node_js:
  - '10'

os:
  - linux

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - printf "@wdtk:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc

install: yarn

script:
  - npm run ci
